[app]
name = "Rainbownick"
menu = "Badge"

[entry]
class = "RainbowNick"

[metadata]
author = "Pietervdvn"
license = "GPL-3.0-or-later"
url = "https://github.com/pietervdvn/flow3r-badge"
description = "A personal nickname with a rotating pride flag"
version = 1
