[app]
name = "Rainbownick"
menu = "Badge"

[entry]
class = "RainbowNick"

[metadata]
author = "Pietervdvn"
license = "GPL-3.0-or-later"
url = "https://git.flow3r.garden/douglas/flag"
description = "Rainbownick"
version = 1
